// Prerequisites are not execution evidence. Live provider checks remain not_run until recorded.

export const PROVIDERS = [
    { id: 'deepl', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'needs DeepL auth or DeepLX' },
    { id: 'bing', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public Microsoft translator endpoint' },
    { id: 'yandex', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public endpoint; may rate-limit' },
    { id: 'openai', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs API key in keychain' },
    { id: 'google', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public translate endpoint' },
    { id: 'transmart', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Tencent Transmart token' },
    { id: 'alibaba', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Alibaba Cloud keys' },
    { id: 'baidu', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Baidu app id/key' },
    { id: 'baidu_field', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Baidu field API keys' },
    { id: 'tencent', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Tencent secret' },
    { id: 'volcengine', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Volcengine keys' },
    { id: 'niutrans', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Niutrans key' },
    { id: 'youdao', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Youdao keys' },
    { id: 'bing_dict', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public dictionary endpoint' },
    { id: 'cambridge_dict', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public dictionary pages' },
    { id: 'caiyun', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Caiyun token' },
    { id: 'chatglm', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Zhipu key' },
    { id: 'geminipro', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Gemini key' },
    { id: 'ollama', kind: 'translate', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs local Ollama daemon' },
    { id: 'ecdict', kind: 'translate', availability: 'local', testStatus: 'not_run', reason: 'local dictionary file' },
    { id: 'lingva', kind: 'translate', availability: 'network', testStatus: 'not_run', reason: 'public Lingva instance' },
    { id: 'system', kind: 'recognize', availability: 'local', testStatus: 'not_run', reason: 'Windows.Media.Ocr' },
    { id: 'tesseract', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs tesseract binary/language data' },
    { id: 'baidu_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Baidu OCR keys' },
    { id: 'baidu_accurate_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Baidu OCR keys' },
    { id: 'baidu_img_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Baidu image OCR keys' },
    { id: 'iflytek_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs iFlytek keys' },
    { id: 'iflytek_intsig_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs iFlytek keys' },
    { id: 'iflytek_latex_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs iFlytek keys' },
    { id: 'simple_latex_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs SimpleTex token' },
    { id: 'tencent_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Tencent OCR keys' },
    { id: 'tencent_accurate_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Tencent OCR keys' },
    { id: 'tencent_img_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Tencent OCR keys' },
    { id: 'volcengine_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Volcengine OCR keys' },
    { id: 'volcengine_multi_lang_ocr', kind: 'recognize', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Volcengine OCR keys' },
    { id: 'qrcode', kind: 'recognize', availability: 'local', testStatus: 'not_run', reason: 'in-process jsQR' },
    { id: 'lingva_tts', kind: 'tts', availability: 'network', testStatus: 'not_run', reason: 'public Lingva TTS' },
    { id: 'edge_tts', kind: 'tts', availability: 'local', testStatus: 'not_run', reason: 'local Edge TTS path' },
    { id: 'anki', kind: 'collection', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs AnkiConnect' },
    { id: 'eudic', kind: 'collection', availability: 'requires_setup', testStatus: 'not_run', reason: 'needs Eudic token' },
];
